import "/public/assets/css/bootstrap.min.css";
import "/public/assets/css/fontawesome.css";
import "/public/assets/css/magnific-popup.css";
import "/public/assets/css/nice-select.css";
import "/public/assets/css/slick-slider.css";
import "/public/assets/css/aos.css";
import "/public/assets/css/mobile-menu.css";
import "/public/assets/css/main.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Recrute - Staffing Agency - Multi-purpose Bootstrap 5 Next.js Template",
    description: "Generated by Recrute - Staffing Agency - Multi-purpose Bootstrap 5 Next.js Template",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="body">{children}</body>
        </html>
    );
}
